### ISSUE TITLE
Images with alpha

### ISSUE THREAD

**Issue by andreamattioli** [ertdfgcvb/Sequencer#4]
To use image with alpha we need to clear canvas just before drawing, something like this inside 'drawImage' function
```
if(/\.(png|gif|bmp|tiff)+$/i.test(img.src)) {
  this.ctx.clearRect(0, 0, this.ctx.canvas.width, this.ctx.canvas.height);
}
```

**Comment by ertdfgcvb** [comment]
@andreamattioli 
That's already the case…?
https://github.com/ertdfgcvb/Sequencer/blob/master/sequencer/sequencer.js#L180

**Comment by andreamattioli** [comment]
You're right!
