### ISSUE TITLE
Support more file name patterns

### ISSUE THREAD

**Issue by ianshade** [ertdfgcvb/Sequencer#8]
Hello, I suggest supporting filenames like "name (1).jpg". It may be very handy as that's how names look after renaming multiple files at once in Windows. Currently the ")" character goes missing.

**Comment by ertdfgcvb** [comment]
Thank you, good request. Currently only numbers at the end of the filename are parsed.

**Comment by ertdfgcvb** [comment]
Fixed & added a test file.
